### ISSUE TITLE
Handle ConnectionLoss when the quorum leader falls

### ISSUE THREAD

**Issue by larribas** [zk-ruby/zk#92]
Hello,

I have a series of Sidekiq workers processing jobs, and I am using Zookeeper to lock certain critical resources. 

Sometimes, the leader of my zookeeper quorum falls, causing a `ZK::Exceptions::ConnectionLoss` on my current connection. When that happens, the lock doesn't get released (because the worker is standing on its own thread, but sharing the same process and connections with others).

Ultimately, this blocks the next jobs that want the resource, until the Sidekiq supervisor is restarted.

This is an example of how my project can be quickfixed:

```ruby
begin
  @zookeeper.with_lock(name) do
    # job...
  end
rescue ZK::Exceptions::ConnectionLoss => e
  @zookeeper.reopen
  retry
end
```

But I wanted to ask... Is that the expected behavior when connecting to Zookeeper? Shouldn't we transparently failover to the next node in the cluster/quorum?
Is there a recommended way of handling it?

Thanks!

**Comment by slyphon** [comment]
So, sometime after ZK was more or less "in the can", the Curator library for Java became the standard thing to use when interacting with zookeeper, mainly because it handles these kinds of cases transparently. This is expected behavior in terms of this client, as it's the behavior of the underlying zkc client, which I took to be the correct behavior. It is admittedly not the most convenient behavior for users, but I didn't feel comfortable making assumptions about user applications and state, i.e. it's better to expose the underlying event rather than take an action that would be incorrect in some way for a given application (like infinite retries or some such). 

What you describe above seems to be the correct fix given the ZK implementation, and there really isn't a better or cleaner way that I can think of.

**Comment by larribas** [comment]
Ok thanks for the feedback!
